### ISSUE TITLE
Dashboard live consumption charts not aligned

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/gingerbase#1]
Hello,

I found a minor issue in the dashboard chart with both Chromium v44 and Firefox 40, those charts are not aligned within the box they belong. Screenshot bellow: 

![image](https://cloud.githubusercontent.com/assets/670087/11502419/e425f01e-9821-11e5-9987-318798c01d3c.png)

My resolution is 1600x900.

**Comment by danielhb** [comment]
@jrziviani I think this bug was fixed in master gingerbase running from source code (Dashboard is not opening in RPM yet). Can you please verify?

**Comment by jrziviani** [comment]
Bug solved

Thank you
