### ISSUE TITLE
Provide an option to delete multiple debug reports at once

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/gingerbase#10]
1)Start kimchi from browser(https://<ip>:8001)
2)Select the host tab\dashboard
3)Click on generate button under debug reports if there are no reports there yet.  Generate several reports if so.  
Suppose that we have more that one debug reports & we want to delete all of them. We need to select report one at a time and click on delete.
Can we provide an option to delete multiple debug reports at once?

**Comment by sstoppler** [comment]
Per discussion w/Aline, here's what's required:
What is needed is to allow the user to select multiple entries in the debug report grid and perform a DELETE request for each item selected. It will imply in changing the grid widget to allow multiple selection and where/how display the delete option to the user.

To follow the RESTful approach, the DELETE option is only allowed in a single resource. Which means, we will not provide any other REST API to delete multiple debug reports in a bunch.

Said that, this issue only requires some work on UI side.

**Comment by samhenri** [comment]
Patch sent to mailing list (must apply patch for Wok first)
