### ISSUE TITLE
Packages update for apt class backend

### ISSUE THREAD

**Issue by peterpennings** [kimchi-project/gingerbase#108]
The apt class is facing some problems when It's updating some packages on ubuntu. At the end of the process the package is updated, but it has still coming back in the packages list (/plugins/gingerbase/host/packagesupdate GET).

**Comment by peterpennings** [comment]
@alinefm @pvital

**Comment by danielhb** [comment]
@pvital can we close this?

**Comment by pvital** [comment]
@danielhb as soon as I work on it, submit a fix, and you commit it upstream :-P
