### ISSUE TITLE
Add a new repo is not intuitive

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/gingerbase#11]
In order to add a new repository it's necessary to select **Actions** of any repository, then click **Add**. It doesn't make much sense because **Add** is not an action to any particular repo.
![image](https://cloud.githubusercontent.com/assets/670087/11719821/9d2bd786-9f43-11e5-98e2-9fd3c6f5da9a.png)

My suggestion is to have a button bellow the **Repositories** title to add a new repo, just like we have in **Software Updates**: 
![image](https://cloud.githubusercontent.com/assets/670087/11719911/16298548-9f44-11e5-8543-1a7e5aa68d3e.png)

**Comment by danielhb** [comment]
Changed my mind about the milestone. This UI can't be launched like this for 2.1.

**Comment by alinefm** [comment]
Fixed by 3441e7ab470658ea7e93544fb072fbdbb95353cf
