### ISSUE TITLE
Locale update broke Dashboard, Updates, Repositories and Debug Reports

### ISSUE THREAD

**Issue by samhenri** [kimchi-project/gingerbase#110]
After the latest commit, the dashboard graph is showing wrong values:

![dashboard](https://cloud.githubusercontent.com/assets/326107/15224610/ce86eb8c-1850-11e6-8e15-7b0ab4f50b49.png)
Console output. Note the NaN values:
![dashboard-console](https://cloud.githubusercontent.com/assets/326107/15224612/d117e05e-1850-11e6-8cc1-b13690ccc3bc.png)

Debug Reports and Repositories:

![debugreports](https://cloud.githubusercontent.com/assets/326107/15224658/097ab30e-1851-11e6-94e6-586a51fd4f58.png)
![debugreports-mobile](https://cloud.githubusercontent.com/assets/326107/15224659/09a36b50-1851-11e6-9954-b3042190215e.png)
![repositories](https://cloud.githubusercontent.com/assets/326107/15224710/407777fc-1851-11e6-81ab-035a9fd79493.png)

Software Updates:
![software_updates](https://cloud.githubusercontent.com/assets/326107/15224712/4486852c-1851-11e6-9de9-c89885b52095.png)

**Comment by danielhb** [comment]
@samhenri which locale have you used? Default portuguese-br? I'll change my locale and see if it's broken here too.

@chandrureddy @archu-s please take a look into this

**Comment by samhenri** [comment]
Tried both English (US) and Portuguese (PT-BR). When switched to Portuguese I've changed the locale to English (US) and got the same result.

**Comment by danielhb** [comment]
Let's move the discussion to the ML:

[ginger-dev-list] Missing text strings and some other bugs after multi-culture patch was applied
