### ISSUE TITLE
Software update is taking too long in F23 

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/gingerbase#111]
This is how long the backend is taking to list the packages to be updated:

```
[danielhb@arthas gingerbase]$ date ; curl -k -u danielhb:passwd -H 'Content-Type: application/json' -H 'Accept: application/json'  'https://localhost:8001/plugins/gingerbase/host/packagesupdate' -X GET ; date
Mon May 16 12:26:32 BRT 2016

(... output of 198 packages to be updated )

Mon May 16 12:31:00 BRT 2016
```

4 and a half minutes.

For comparison, this is how long dnf update takes to execute:

```
[danielhb@arthas gingerbase]$ date ; sudo dnf update ; date 
Mon May 16 12:35:18 BRT 2016
Last metadata expiration check: 2:04:32 ago on Mon May 16 10:30:46 2016.
Dependencies resolved.
=================================================================================================
 Package                        Arch   Version              Repository                      Size
=================================================================================================
Installing:
 kernel                         x86_64 4.4.9-300.fc23       updates                         58 k
 kernel-core                    x86_64 4.4.9-300.fc23       updates                         20 M
 kernel-modules                 x86_64 4.4.9-300.fc23       updates                         18 M
 python2-pysocks                noarch 1.5.6-3.fc23         updates                         24 k
 python3-pysocks                noarch 1.5.6-3.fc23         updates                         25 k
Upgrading:
 adwaita-qt-common              noarch 0.4-1.fc23           updates                        305 k
(...)
Transaction Summary
=================================================================================================
Install    5 Packages
Upgrade  198 Packages
Remove     3 Packages

Total download size: 784 M
Is this ok [y/N]: N
Operation aborted.
Mon May 16 12:35:20 BRT 2016
```

2 seconds.

Yes, I am aware that our backend is doing some sort of lookup in each package to retrieve its dependencies. But to the user point of view it is 4 and 1/2 minutes versus 2 seconds. 

We need to review this design because for any host with 400+ packages to be updated (it's not that unusual. I've updated all the packages of this F23 box last week and ATM I am sitting at 198 packages to be updated) it's very likely that the WoK session would expire before the package listing is retrieved.

**Comment by alinefm** [comment]
It is because, for each package returned, we query the package dependencies.
I agree it is not a good design so my proposal is to remove the 'dependencies' as part of the GET /packagesupdates API and create a new one GET /packagesupdates/<package>/deps to exclusively query the package dependencies.

On UI, when user selects only a few packages to be updated, we need to get all the dependencies by using the new API (/packagesupdates/<package>/deps) and add a confirmation box to user continue or not. This confirmation box already exists today, we will only need to modify the way to get the information to fill it up.
