### ISSUE TITLE
User Experience: Show progress bar while generating debug reports

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/gingerbase#117]
From my experience I see many of the tasks run background with spin wheel for longer durations but do not give any clear picture of the progress of the functionality triggered.
I feel task API is one very good example of background taks initiated/monitored.  Providing the progress of the background task to the user from UI will improve the user experience.
For e-g 
1. Under Wok -> Dashboard -> Debug Report -> Generate action  creates debug report where the task is running in back end which notifies UI after completion however in between how much progress background taskmade is not known to user ie. via UI.
![debug_1](https://cloud.githubusercontent.com/assets/511072/16038042/d624c6ca-3240-11e6-82b5-ce6194713285.png)

existing functionality:

![debug_2](https://cloud.githubusercontent.com/assets/511072/16038054/f01afc98-3240-11e6-87e6-0fde4a702049.png)

New functionality : 
can we add one more field showing some progress in percentage

![debug_3](https://cloud.githubusercontent.com/assets/511072/16039547/239416fc-3248-11e6-9625-13fa1497d048.png)
1. similarly under Update tab we have software updates > "update  all" and Repositories > Remove actions which sometimes takes time for completion and which were tracked by task API, So good idea to show the progress in such case.

**Comment by alinefm** [comment]
Hi @rajatgupta21 

I understand and agree your point. But in that case, while generating a debug report, there is no way to identify how much was done or not to show a progress bar on UI.
We use sosreport command and it does not provide any way to check the progress while it is running.

I have restricted this issue for the debug report generation so we can properly discussed on that.
IMO we can not treat all cases as the same as there are some cases there is no way to add progress bar.
Please, open separated issues for the other cases you have noticed a progress bar would be good.

**Comment by alinefm** [comment]
Closing this issue based on last comment and inactivity.
