### ISSUE TITLE
Loading icon appears on Update tab content when both sections are collapsed 

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/gingerbase#121]
1. Go to Updates tab under Host tab
2. An loading icon is displayed on main content even those the sections are collapsed.

![9e3add015330441](https://cloud.githubusercontent.com/assets/4921718/16622558/f6f881a2-4370-11e6-81d4-06dd510b0368.jpg)

I was able to open/close both sections. But when opining the "Software Updates" section I got the below result.

![28d063432cd29030](https://cloud.githubusercontent.com/assets/4921718/16622611/1b260a0e-4371-11e6-9ce7-3b44c0c1f688.jpg)

The loading icon should be displayed inside the section and ONLY if it is open.

**Comment by samhenri** [comment]
A patch was sent to Wok to prevent this on Jul 6th and then I rebased it and sent a v2 this Tuesday.
