### ISSUE TITLE
Unable to edit/delete/enable/disable repositories when "Software Updates" section is loaded

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/gingerbase#122]
1. Go to "Updates" tab under Host tab
2. Open "Repositories" section
3. Wait until it loads the content
4. Select any repository
5. The buttons to enable/disable, remove and edit will be enabled
6. Open "Software Updates" section.
7. Wait until it loads the content.
8. Go back to "Repositories" section
9. Select any repository.
10. ONLY the remove button will be enabled.
    The enable/disable and edit buttons should be enabled too.

**Comment by pvital** [comment]
Hello @samhenri 

Any update related to this issue?

**Comment by samhenri** [comment]
Hi, I'm currently working on other issues that were tagged with higher priority. I noticed some bugs with wok.list.js but they're not related.

**Comment by pvital** [comment]
This issue still happens with https://github.com/lcorreia/gingerbase/commit/b51c6ae7a0ff08b4eca2c1382e8a72ba34fb91ec

**Comment by biancafc** [comment]
Also having this issue with [lcorreia@b51c6ae](https://github.com/lcorreia/gingerbase/commit/b51c6ae7a0ff08b4eca2c1382e8a72ba34fb91ec) in Fedora 24.

**Comment by alinefm** [comment]
Both sections, repositories and updates, make use of wok.list.js widget.
This widget is responsible for select the options on mouse click and it is searching the whole page for checked elements instead of doing that only on a given element/section.
I will send a patch to Wok to fix that. I also identified some minor issues on dashboard HTML which I will send a patch to fix too.
