### ISSUE TITLE
'_ ' shouldbe allowed or not for debug report creation.

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/gingerbase#126]
The debug report generation comprises of compression of sosreport
 and Dbginfo report for s390x machines and generation of only sosreport for x86 machines. The sosreport
 command  allows to give name with underscore meaning I can execute #sosreport --batch --name=test_sosreport
  However it generate the corresponding sosreport with name sosreport-testsosreport-20151103134451.tar.xz
 i.e. the underscore is removed in case the sosreport encounters a underscore in the name. Since the
 ("_") is removed the searching for the sosreport  with the same name in the folder fails.We had come up with a solution wherein if the debug report name had an underscore we replaced the ("_") with space
  sosreport_name = name.replace('_', '') , but according to Aline's suggestion .
  " If underscore character is not allowed we should block user to use and raise an appropriated error
   message instead of changing user's input without any previous warning." Therefore we implemented the same in
  the backend wherein an exception is raised when ("_") is present in the debug report name. Since the backend does not
  allow ("_") according  to me the same  should be provided from the UI to restrict the users from entering ("_") in the debug report name.

On the other hand we can for sure take care of the underscore ("_") as sosreport command allow _ and does not throw any exception, the code should also able to handle this scenario. Need to discuss on this.

**Comment by danielhb** [comment]
If the sosreport command line tool allows the '_' we need to understand why this scenario is failing in our code and fix it.

If it doesn't then we need to forward the error message from the command line to the user interface.

Reading you message I am not sure which scenario are we talking about here. Is it (1) ?

**Comment by mesmriti** [comment]
yes. the sosreport command line allows the "_" but then when creating the tar file it removes the provided "_". For ex. if th einput is test_report it creates the sosreport with the name testreport.tar.tz.
The code keeps searching for the for the sosreport with the same name (test_report) which is not found as the name has been changed to testreport.tar.xz and therefore the creation of sosreport fails in case of "_" as input in debug report.

**Comment by danielhb** [comment]
The good course of action here is to create the tar with the '_' as intended. If there is some caveat we can reassess

**Comment by potula-chandra** [comment]
Megha, I agree with @danielhb .

To be precise, 
If user provided ' _ ' for the debug report and generated sos report removes " _ " then our code should handle this explicitly to match with the user input.

**Comment by mesmriti** [comment]
Agreed. Will take care of the same from the backend.
