### ISSUE TITLE
Port 8010 is not listening

### ISSUE THREAD

**Issue by daniel-lucio** [kimchi-project/gingerbase#128]
who is the responsible to open the 8010? I can find that

**Comment by thesabbir** [comment]
same here

**Comment by pvital** [comment]
Hello @daniel-lucio 

Generally it's not necessary open port 8010. Have you tried to configure your firewall and/or check the SELinux? See if some of this tips help you: https://github.com/kimchi-project/wok/blob/master/docs/troubleshooting.md

**Comment by daniel-lucio** [comment]
Thank you,  it seems that the wokd daemon was not running :)

**Comment by pvital** [comment]
@daniel-lucio that's nice.
Please, check if it was wokd.service problem  and let us informed here.

**Comment by daniel-lucio** [comment]
The problem was RPM didn't start it automatically, and I didn't know about wokd. The reboot enlightened me to know wokd existence.
