### ISSUE TITLE
Help pages split 

### ISSUE THREAD

**Issue by potula-chandra** [kimchi-project/gingerbase#14]
Help pages split as per new tabs dashboard and updates has to be done other wise help content will not be fetched and you could see following error message.

![572d1a98-9fe2-11e5-8424-78a3489da56d](https://cloud.githubusercontent.com/assets/10830725/11743791/5afdfa54-a030-11e5-8e38-8089c78e1736.png)

**Comment by danielhb** [comment]
Issue fixed
