### ISSUE TITLE
No Option for LVM Logical Volumes

### ISSUE THREAD

**Issue by RocketMaun** [kimchi-project/gingerbase#149]
I'm evaluating Kimchi project for the first time.
I see the API and source code have entries for logical volume management, but as far as I can tell there's no way to manage logical volumes in the interface.

I only see volume groups:
![logical_volumnes](https://cloud.githubusercontent.com/assets/23329665/20088626/6fef2f4e-a54f-11e6-9f70-e40fd9cfe963.png)

Is there a bug? Can anyone tell me if there is support for Logical Volume management in this interface?

**Comment by danielhb** [comment]
@RocketMaun if I recall correctly the LVM management is being done together with the Volume Group management. We've created a wizard in this feature that contemplates both.

@atreyeemukhopadhyay can you comment on this? Are we managing LVMs together with VMs or are we lacking LVM support in the UI?

**Comment by ramonmedeiros** [comment]
Merged at ginger repo:

dab1560a106b7c3800407382461243d9751afd7c
