### ISSUE TITLE
Service start doesn't works when system's language is not English

### ISSUE THREAD

**Issue by the-question** [kimchi-project/gingerbase#18]
_lscpu.py_ expects _lscpu_ command to return a line with "Core(s) per socket" in it.  
When the system's local isn't English (French for example), this isn't the case: a french system gives "Cœur(s) par socket".

This lead to a **wok.exception.NotFoundError: GGBCPUINF0005E: GGBCPUINF0005E** error when trying to start wok's service (systemctl start wokd.service).

**Comment by danielhb** [comment]
I'll look into it

**Comment by danielhb** [comment]
I've fixed this problem in upstream code. Can you try it out?

**Comment by the-question** [comment]
d78e65b93c1f03a67d21d7a41304b19e9b755f85 correctly fixes this issue. I think you can close it.

P.S.: I haven't checked other uses of "run_command", they may also need a small correction.

**Comment by danielhb** [comment]
@the-question I was thinking about changing the run_command function to always enforce the default language to avoid these cases where the different system language might break the parsing of the output. I'll suggest this change to the WoK community.

Let me know if you still find problems running Ginger (or any of the other Kimchi-project plug-ins) in a French environment.

Thanks!
