### ISSUE TITLE
Software update fails with 500 status code when host is up to date

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/gingerbase#19]
Architecture: x86 and s390x
OS: Fedora and KVM for IBM z Systems

Currently when system is up to date with all packages, /plugins/gingerbase/swupdate returns 500 status code. Ideally it should be successful operation returning 200.

[suresh@localhost ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{}' 'https://127.0.0.1:8001/plugins/gingerbase/host/swupdate'
Enter host password for user 'root':
{
  "reason":"GGBPKGUPD0001E: No packages marked for update",
  "code":"500 Internal Server Error"
}

**Comment by pvital** [comment]
@danielhb please assign this issue to me.

**Comment by pvital** [comment]
Solution is upstream. Can close this issue.
