### ISSUE TITLE
[regression] Software update looses the progress the Updates tab is reloaded

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/gingerbase#20]
After login, navigate to **"Updates"** tab. You must have repository(ies) enabled with software available to upgrade.

Click **"Update All'** to start the process, then navigate to any other tab, and go back to **"Updates"** tab. You will see that there will be no upgrade progress being displayed.

**Comment by danielhb** [comment]
A fix was pushed upstream. Please check if this issue is fixed.

**Comment by jrziviani** [comment]
Fixed :)
