### ISSUE TITLE
Not able to rename a debug report

### ISSUE THREAD

**Issue by pvital** [kimchi-project/gingerbase#22]
When trying to rename a debug report, nothing happens on UI and error messages raises on background screen.

How to reproduce:
1 - once logged in, select Host->Dashboard tabs
2 - for any debug reported listed, select Actions->Rename
3 - on new screen, rename the debug report and click on Submit button

Nothing happens after that. If the Submit button is clicked only once, the error message "Nothing matches the given URI". If the Submit button is clicked twice, the error message "GGBDR0001E: Debug report blablebli does not exist".

![screenshot from 2015-12-28 16-09-04](https://cloud.githubusercontent.com/assets/699330/12023225/78061716-ad7e-11e5-97e3-4d5a0589e643.png)

If I change to a diffente tab and move back to Dashboard, I can see the debug report renamed. Tested on a Fedora 23 host machine.

**Comment by danielhb** [comment]
Can you check if the debug report rename works using the backend?

**Comment by danielhb** [comment]
Nvm just read the full text of the issue lol

This is an UI bug

**Comment by alinefm** [comment]
Fixed by f4f49c143cbfd1df05ced3283328ead45335879a
