### ISSUE TITLE
Cannot use mouse after generate a Debug Report using Firefox

### ISSUE THREAD

**Issue by pvital** [kimchi-project/gingerbase#24]
It's not able to use the mouse after request to generate a new Debug Report. Looks like the screen is working because the graphs in Dashboard tab are still updating, but the mouse lost its capability to click on any link.

How to reproduce:
1. Select Host->Dashboard tab
2. Under Debug Reports table, select Actions->Generate
3. Enter a report name and click on Generate button
4. Try to click on any link/button

Only after refresh the page (F5 or Ctrl+R) the mouse goes back to work. Tested using Firefox 43 browser provided by Fedora 23 package system.

**Comment by alinefm** [comment]
Hi @pvital 

I could not reproduce it on 188db297608671d39b8b5bbdee23caf04cc1d620
I was able to generate a debug report, switch tabs and go back to Dashboard tab without any issue.

Could you try it again and provide your results here?

**Comment by pvital** [comment]
It's working now. Closing
