### ISSUE TITLE
Cannot list available packages to system update on Ubuntu 15.10

### ISSUE THREAD

**Issue by pvital** [kimchi-project/gingerbase#25]
When using the UI to upgrade an Ubuntu 15.10 system, the list is not provided by the following error:

An error occurred while retrieving system information. GGBPKGUPD0003E: Error while getting packages marked to be updated. Details: E:Not locked

![screenshot from 2015-12-29 16-00-44](https://cloud.githubusercontent.com/assets/699330/12039346/d1a5dcc0-ae46-11e5-8869-867d624d3ebd.png)

Got the same error when trying to get the list of available packages using REST command:

```
$  curl -k -u test -H "Content-Type: application/json" -H "Accept: application/json" 'https://192.168.122.155:8001/plugins/gingerbase/host/packagesupdate' -X GET
Enter host password for user 'test':
{
  "reason":"GGBPKGUPD0003E: Error while getting packages marked to be updated. Details: E:Not locked",
  "code":"500 Internal Server Error",
  "call_stack":"Traceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py\", line 670, in respond\n    response.body = self.handler()\n  File \"/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py\", line 217, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py\", line 61, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"/home/test/wok/src/wok/control/base.py\", line 363, in index\n    raise cherrypy.HTTPError(500, e.message)\nHTTPError: (500, u'GGBPKGUPD0003E: Error while getting packages marked to be updated. Details: E:Not locked')\n"
}
```

**Comment by pvital** [comment]
UPDATE: after re-start wokd I could get the list of available packages to ugrade. May be it's an expected behaviour when apt is not locked.

**Comment by danielhb** [comment]
Makes sense to need the apt lock but this error message sucks

**Comment by danielhb** [comment]
A fix was pushed upstream. Please check if this issue is fixed.

**Comment by pvital** [comment]
Yes, it was fixed by patch-set submitted by @jrziviani
