### ISSUE TITLE
[Enhancement] Blank dashboard for non admin users

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/gingerbase#29]
I created an user to access wok without admin permission (not in sudoers). After login user that user account I got a blank **Dashboard**:
![image](https://cloud.githubusercontent.com/assets/670087/12151154/d3d9f3a6-b494-11e5-9228-83fcf04c5523.png)

I think there is not problem to show dashboard content that doesn't need admin rights.

**Comment by alinefm** [comment]
From the tab-ext.xml file:

`<?xml version="1.0" encoding="utf-8"?>                                          
<tabs-ext>                                                                      
    <functionality>Host</functionality>                                         
    <tab>                                                                       
        <access role="admin" mode="admin"/>                                     
        <access role="user" mode="read-only"/>                                  
        <title>Dashboard</title>                                                
        <order>0</order>                                                        
        <path>plugins/gingerbase/tabs/host-dashboard.html</path>                
    </tab>                                                                      
    <tab>                                                                       
        <access role="admin" mode="admin"/>                                     
        <access role="user" mode="none"/>                                       
        <title>Updates</title>                                                  
        <order>20</order>                                                       
        <path>plugins/gingerbase/tabs/host-update.html</path>                   
    </tab>                                                                      
</tabs-ext>`

Which means the Dashboard tab should appear on read-only mode, ie, the user will not be able to generate a debug report or download one.

**Comment by alinefm** [comment]
Hi @jrziviani 

I could not reproduce it on 188db297608671d39b8b5bbdee23caf04cc1d620
I was able to see host statistics and basic information. The debug report session is hidden as a normal user can not do anything on that.

Could you retest and provide your results here?

**Comment by jrziviani** [comment]
Yes, this bug was opened before the modifications you told and now it looks much better. I'm closing it.
