### ISSUE TITLE
Tests failing @ Fedora 23

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/gingerbase#3]
These unit tests are failing running in F22 x86_64:
# 
## FAIL: test_nonroot_access (test_authorization.AuthorizationTests)

Traceback (most recent call last):
  File "test_authorization.py", line 63, in test_nonroot_access
    self.assertEquals(403, resp.status)
AssertionError: 403 != 200
# 
## FAIL: test_uninstalled_plugin_paths (test_config.ConfigTests)

Traceback (most recent call last):
  File "test_config.py", line 66, in test_uninstalled_plugin_paths
    % prefix)
AssertionError: '/etc/wok/plugins.d' != '/usr/share/wok/src/wok/plugins/gingerbase'

---

**Comment by pvital** [comment]
@danielhb is it necessary all tests running on Fedora 22 since 23 is the current official release?

**Comment by danielhb** [comment]
Nope but I kept this issue opened because the failing tests had nothing to do with distro and would fail with F23 too

**Comment by danielhb** [comment]
These are the tests failing @ F23. I'll update the bug description to reflect that

```
======================================================================
ERROR: test_hostinfo (test_host.HostTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_host.py", line 77, in test_hostinfo
    self.assertEquals(psutil.TOTAL_PHYMEM, info['memory']['online'])
AttributeError: 'module' object has no attribute 'TOTAL_PHYMEM'

======================================================================
FAIL: test_uninstalled_plugin_paths (test_config.ConfigTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_config.py", line 66, in test_uninstalled_plugin_paths
    % prefix)
AssertionError: '/etc/wok/plugins.d' != '/usr/share/wok/src/wok/plugins/gingerbase'

----------------------------------------------------------------------
Ran 24 tests in 24.660s

FAILED (failures=1, errors=1)
[danielhb@arthas tests]$ 
```

**Comment by danielhb** [comment]
Fixed in master branch
