### ISSUE TITLE
Software Update Progress freezes when session timeout'ed.

### ISSUE THREAD

**Issue by pvital** [kimchi-project/gingerbase#39]
After start a host Software Update with a huge number of packages to update that takes more time to finish than the UI session timeout parameter, the screen freezes (no update no Software Update Progress window) with no information to user. 

User needs to change to a different tab to UI check that session closed (Wok session timeout is set to 5 or 10 minutes, I guess) and then prompt message and move to login screen.

**Comment by danielhb** [comment]
One solution would be to make this an asynchronous task

We can also increase the timeout but this would affect the other plug-ins. I wouldn't recommend it.

**Comment by pvital** [comment]
The SoftwareUpdateProgress class (the one responsible to get the output of the package manager when running) is an AsyncReource.

**Comment by laggarcia** [comment]
I think the issue here is a pure UI issue. The UI is updating itself while the software update is running as async task. When the session timeout, the UI just stops to receive updates and doesn't do anything about that. It should at least redirect the user to the login script when that happens (the UI requests updates and don't receive anything back)

**Comment by pvital** [comment]
I agree with @laggarcia that it's a pure UI issue.

**Comment by danielhb** [comment]
Removed 'backend' from the issue tags

**Comment by alinefm** [comment]
Hi @pvital 

I could not reproduce it on 188db297608671d39b8b5bbdee23caf04cc1d620

Could you retest and provide your results here?

**Comment by pvital** [comment]
The main issue (timeouted session and page still "open") is fixed. I selected to update a Fedora 24 system (44 packages) running 188db29. The system started to download packages and after session timeout, the login page was loaded with the timeout error reported on it.

However, login again, the landing page was the Software Update and the loading wheel was in a infinite loop with no feedback. Looks like the dnf was still updating the system in background and UI could not process it. The following message was printed on wok-error.log file:

GGBPKGUPD0005E: There is a package manager instance running in the system.

**Comment by pvital** [comment]
Closing this since the main issue was fixed.
Opened issue #125 to handle the problem reported on comment above.
