### ISSUE TITLE
rpm creation failed on Fedora 23

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/gingerbase#4]
Originally report at https://github.com/kimchi-project/kimchi/issues/779

make[4]: **\* No rule to make target 'src/gingerbase.scss', needed by 'gingerbase.css'. Stop.
make[4]: Leaving directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0/ui/css'
Makefile:372: recipe for target 'all-recursive' failed
make[3]: **\* [all-recursive] Error 1
make[3]: Leaving directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0/ui'
Makefile:606: recipe for target 'all-recursive' failed
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0'
Makefile:443: recipe for target 'all' failed
make[1]: **\* [all] Error 2
make[1]: Leaving directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0'
error: Bad exit status from /var/tmp/rpm-tmp.RRMRzq (%build)

**Comment by potula-chandra** [comment]
Working on this ticket. Will be sending patch soon !!!

**Comment by danielhb** [comment]
Patch applied to remote master/next
