### ISSUE TITLE
Update page displays blank and debug reports is not displayed in UI

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/gingerbase#40]
OS: Fedora 21, KVM for IBM z Systems Architecture:x86, s390x

![screenshot from 2016-01-25 13 55 39](https://cloud.githubusercontent.com/assets/12499230/12545812/5e661b50-c36b-11e5-8cd9-b1c2d43823c8.png)

![screenshot from 2016-01-25 13 55 43](https://cloud.githubusercontent.com/assets/12499230/12545813/5ead7432-c36b-11e5-9357-54fbbdff8b5d.png)

**Comment by sureshab** [comment]
i will be working on this issue

**Comment by potula-chandra** [comment]
Issue solved. Please close this ticket
