### ISSUE TITLE
Misleading CPU numbers in Basic Information when SMT (multithreading) active.

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/gingerbase#42]
Architecture:s390x, OS: KVM for IBM z Systems

When SMT is enabled, the CPU information is misleading:

Online: 8, Offline: 0, Shared: 4, Dedicated: 0
 CPU(s)

Its showing 8 CPUs, but when it comes to shared and dedicated only 4 are being shown.

The inconsistency is caused by:
- the total number of CPUs is gathered via lscpu which is returning the number of
  threads. Handling threads as CPUs is consistent here with other platforms.
            [root@zs95k4 ~]# lscpu
            Architecture:          s390x
            CPU op-mode(s):        32-bit, 64-bit
            Byte Order:            Big Endian
            CPU(s):                8
            On-line CPU(s) list:   0-7
            Thread(s) per core:    2
            Core(s) per socket:    8
            Socket(s) per book:    3
            Book(s):               8
            Vendor ID:             IBM/S390
- the number of shared/dedicated CPUs is gathered from /proc/sysinfo and here
  we have the LPAR cores:  
            [root@zs95k4 ~]# cat /proc/sysinfo
            ................................................
            LPAR CPUs Total:      4
            LPAR CPUs Configured: 4
            LPAR CPUs Standby:    0
            LPAR CPUs Reserved:   0
            LPAR CPUs Dedicated:  0
            LPAR CPUs Shared:     4

I guess we need to add the information about the threads for clarification.
Here a proposal on how we could display the information:

Online: 8, Offline: 0 
 CPU(s)

Shared: 4, Dedicated: 0
Core(s)

Thread(s) per Core: 2

**Comment by sureshab** [comment]
please assign this issue to me.

**Comment by sureshab** [comment]
@danielhb 
in x86 and ppc we do not have shared/dedicated cpu information so online cpus is the only count which will be displayed for user. However in "s390x" we have additional shared and dedicated information where the information is misleading with the count when simultaneous multi-threading  is enabled.

If you agree to add Thread(s) per core information described in issue we can add it for all platforms since hyper threading/SMT is applicable for all the architectures. This would add an additional JSON attribute for /plugins/gingerbase/host api.

**Comment by danielhb** [comment]
Is there a default, multi-arch way to get this Thread per Core info?

**Comment by sureshab** [comment]
lscpu gives this information in x86 and s390x,,not sure about ppc,, could you check it out?

**Comment by danielhb** [comment]
```
$ lscpu
Architecture:          ppc64le
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    8
Core(s) per socket:    4
Socket(s):             4
NUMA node(s):          4
Model:                 8284-22A
L1d cache:             64K
L1i cache:             32K
L2 cache:              512K
L3 cache:              8192K
NUMA node0 CPU(s):     0-31
NUMA node1 CPU(s):     32-63
NUMA node16 CPU(s):    64-95
NUMA node17 CPU(s):    96-127
```

Yeah, it appears that lscpu provides this info for pSeries as well

I believe you can go on and add this new info for all archs

**Comment by sureshab** [comment]
thank you,,I will add this as new attribute to /plugins/gingerbase/host api json and will make the corresponding UI changes.

**Comment by pvital** [comment]
@sureshab, the patch you submitted to ML looks good and it's working, but IMO the unique information about the threads per core isolated is not given more information to user.

For example, in my case. My laptop has 1 socket, with 2 cores per socket and 2 threads per core, totaling 4 CPUs. With your patch I have only the information:

```
Online: 4, Offline: 0
CPU(s)

2
Thread(s) per Core
```

I guess would be better add the other information provided by lscpu, in a line bellow the Online/Offline information, like:

```
Online: 4, Offline: 0
Sockets: 1, Core per sockets: 2, Thread(s) per Core: 2
CPU(s)
```

You will concentrate all the CPU information in the same block in the screen and provide more information to the user. Think in the other systems like Power (ppc) and S390x, that have more sockets and cores then a simple laptop. For example, in a Power machine the information
would be like:

```
Online: 128, Offline: 0
Sockets: 4, Core per sockets: 4, Thread(s) per Core: 8
CPU(s)
```

That provides the information to user that all 4 sockets are connected. But if the admin turn off one of them (I not sure if it's possible but only to exemplify the case):

```
Online: 96, Offline: 32
Sockets: 4, Core per sockets: 4, Thread(s) per Core: 8
CPU(s)
```

with this information, I can calculate that 1 socket is not working. If 1 core is not working, the number would be Online: 120, Offline: 8.

**Comment by sureshab** [comment]
@pvital 
incorporated your suggestions and sent a patch to ML. Latest patch includes number of Book(s) information for "s390x" architecture.

**Comment by danielhb** [comment]
Patch was pushed upstream. Please test it and close the bug if the results are adequate

**Comment by sureshab** [comment]
patch works fine and provides required details.
