### ISSUE TITLE
Action->Add you have 2 info notes under options that refer to DEB repos. We are still on RHEL so yum

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/gingerbase#44]
Goto Updates Tab
Select an Actions Add next to which ever repos
Under the updatable Options you will see an i icon for info

You refer to the repos as a DEB repos when really we are running on RHEL with a yum repos.
I would make them more generic esp if when we rebase to Zeus this would change.

**Comment by alinefm** [comment]
Duplicated of #135
