### ISSUE TITLE
The interface for Actions under the Updates Panel is inconsistent and does not make sense.

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/gingerbase#45]
Issue is that if you look at Updates Panels and under that Repositories
Each repos listed has an "Action" pull down next to it.
On the other panels you have a high level actions button on top
Then a selection to perform an action against it.
You also have an "Add"
The add is the most confusion of all because you have to select an already existing repos to add a new one which makes no sense.

**Comment by alinefm** [comment]
Duplicated of #11
