### ISSUE TITLE
Edit does not work on an existing repos

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/gingerbase#46]
From the Updates Panel under Repositories
Select Actions Next to target repos and Edit
Make any change that it allows as some fields are not allowed
Save

Nothing changes and the pop up window stays open and the Save Button becomes enable again. 

I reopened the Repos again with Edit and the Old data was still there.
I checked under yum.repos.d and the file is unchanged as well.

**Comment by alinefm** [comment]
Hi @mesmriti 

Please, provide details information on how to reproduce this issue.
Which OS (yum or apt-get system) ?

**Comment by alinefm** [comment]
Is it duplicated of #21 ?

**Comment by mesmriti** [comment]
yes its the replica of #21 .
