### ISSUE TITLE
UI allows renaming of debug report to empty string

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/gingerbase#48]
UI allows debug report to be renamed to empty string. The result is the following:

wok/src/wok/plugins/gingerbase/data/debugreports/test0.tar.xz renamed to wok/src/wok/plugins/gingerbase/data/debugreports/.tar.xz

And that debug report is not listed anymore by the UI.

**Comment by lcorreia** [comment]
Sent patch to ML.

**Comment by danielhb** [comment]
Fixed by

https://github.com/kimchi-project/gingerbase/commit/418db60f52948a2074c17210e35e17dcf919afbf
