### ISSUE TITLE
Debug reports to support s390x platform

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/gingerbase#6]
Originally reported on https://github.com/kimchi-project/kimchi/issues/749

Current upstream code just collects sosreport and tar is moved to /var/lib/kimchi/debugreports.
For s390x platform, dbginfo also need to be collected by running dbginfo.sh along with sosreport.
And final tar of sosreport and dbginfo should get collected and moved to /var/lib/kimchi/debugreports.

From @laggarcia 
I know this is not related to Kimchi/Ginger, but ideally I think dbginfo call should be included as a plugin to sosreport.

**Comment by danielhb** [comment]
@chandrureddy  we shall consider this enhancement as part of Z effort. I do not believe this is a new feature, it's more like a bug, so we don't need to worry about D-CUTs or whatever.

**Comment by potula-chandra** [comment]
Yes. Soon patch will be sent to take of small comments received from aline !!!

**Comment by danielhb** [comment]
@chandrureddy I believe this issue is already fixed. Can you confirm?

**Comment by alinefm** [comment]
Probably fixed by 518fae03 (?)

**Comment by potula-chandra** [comment]
Yes Daniel, it is taken care. We can close the ticket !!!
