### ISSUE TITLE
No option provided to update selected packages only

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/gingerbase#9]
1)select kimchi from browser
2)Select hosts tab\updates.  Under Software updates, there is no option to select a package and update only that package.

  Can we provide an option to updated selected packages only?

**Comment by pvital** [comment]
I'm going to start the development of a solution for backend.

@sstoppler, will keep you informed about the changes in backend, then you will be able to start the updates in UI.

**Comment by pvital** [comment]
V1 of backend patch-set submitted to ML.

**Comment by pvital** [comment]
Backend code already committed. Time for UI improvements :-)

**Comment by alinefm** [comment]
UI code: 760a5d1ae974f0e68d8d25c1bd12634282edfade
